apiVersion: v1
kind: Service
metadata:
  labels:
    run: api
  name: api
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
    - name: api-port
      port: 80
      targetPort: 80