apiVersion: v1
kind: Service
metadata:
  labels:
    app: fruit
  name: fruit
  namespace: default
spec:
  type: NodePort
  selector:
    app: fruit
  ports:
    - name: fruit-port
      port: 2000
      targetPort: 2000
